import { Activity, AlertTriangle, BarChart3, BookOpenCheck, History, ListChecks } from "lucide-react"
import { useState } from "react"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { EquityDrawdownChart } from "@/features/strategy-lab/equity-drawdown-chart"
import { CurrentSignalPanel } from "@/features/strategy-lab/current-signal-panel"
import type { BacktestResult, ParameterSearchResponse } from "@/lib/types"
import { cn } from "@/lib/utils"

function number(value: number | null | undefined, suffix = "", decimals = 2) {
  return value === null || value === undefined || !Number.isFinite(value) ? "—" : `${value.toFixed(decimals)}${suffix}`
}

function MetricCard({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: "positive" | "negative" }) {
  return <div className="rounded-lg border bg-background/50 p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className={cn("mt-2 text-2xl font-semibold", tone === "positive" && "text-primary", tone === "negative" && "text-destructive")}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>
}

function TradeHistoryPreview({ result, onOpen }: { result: BacktestResult; onOpen: () => void }) {
  const recentTrades = [...result.trades].reverse().slice(0, 5)
  return <Card className="gap-3 py-4"><CardHeader className="px-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><History className="size-4 text-primary" /><CardTitle className="text-base">Trade History</CardTitle><Badge variant="secondary">{result.trades.length}</Badge></div><CardDescription className="mt-1">Recent entries, exits, open marks, and realized or unrealized P&amp;L.</CardDescription></div><Button size="sm" variant="outline" onClick={onOpen}>View All Trades<History /></Button></div></CardHeader><CardContent className="px-4"><div className="overflow-x-auto"><Table><TableCaption className="sr-only">Recent strategy trades.</TableCaption><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Entry</TableHead><TableHead>Exit / As Of</TableHead><TableHead>P&amp;L</TableHead><TableHead>Return</TableHead></TableRow></TableHeader><TableBody>{recentTrades.map((trade, index) => <TableRow key={`${trade.entryDate}-${index}`}><TableCell><Badge variant={trade.status === "Open" ? "secondary" : "outline"}>{trade.status}</Badge></TableCell><TableCell>{trade.entryDate} · ${number(trade.entryPrice)}</TableCell><TableCell>{trade.exitDate || trade.asOfDate || "—"} · ${number(trade.exitPrice)}</TableCell><TableCell className={cn(trade.pnl >= 0 ? "text-primary" : "text-destructive")}>{number(trade.pnl)}</TableCell><TableCell className={cn(trade.pnlPercent >= 0 ? "text-primary" : "text-destructive")}>{number(trade.pnlPercent, "%")}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
}

function Overview({ result, runLabel, onOpenTrades }: { result: BacktestResult; runLabel: string; onOpenTrades: () => void }) {
  const metrics = result.metrics
  const excess = metrics.excessReturn || 0
  return <div className="space-y-5">
    <Alert className="border-primary/25 bg-primary/5"><BookOpenCheck /><AlertTitle>{result.verdict.label}</AlertTitle><AlertDescription><p>{result.verdict.reason}</p><p>{result.explanation}</p></AlertDescription></Alert>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Strategy Return" value={number(metrics.totalReturn, "%")} detail={runLabel || result.strategy.name} tone={metrics.totalReturn >= 0 ? "positive" : "negative"} />
      <MetricCard label="Vs Buy & Hold" value={number(excess, "%")} detail={`Passive return ${number(metrics.benchmarkReturn, "%")}`} tone={excess >= 0 ? "positive" : "negative"} />
      <MetricCard label="Maximum Drawdown" value={number(metrics.maxDrawdown, "%")} detail={`${number(metrics.timeUnderwater, " sessions", 0)} underwater`} tone="negative" />
      <MetricCard label="Market Exposure" value={number(metrics.exposure, "%", 1)} detail={`${metrics.trades} closed · ${metrics.openTrades} open trades`} />
      <MetricCard label="Sharpe Ratio" value={number(metrics.sharpeRatio)} detail={`Sortino ${number(metrics.sortinoRatio)}`} />
      <MetricCard label="Calmar Ratio" value={number(metrics.calmarRatio)} detail={`CAGR ${number(metrics.cagr, "%")}`} />
      <MetricCard label="Win Rate" value={number(metrics.winRate, "%", 1)} detail={`Profit factor ${number(metrics.profitFactor)}`} />
      <MetricCard label="Execution Costs" value={number(metrics.totalExecutionCosts, "", 2)} detail={`Ending capital ${number(metrics.endingCapital, "", 0)}`} />
    </div>
    <CurrentSignalPanel signal={result.currentSignal} trades={result.trades} />
    {!!result.qualityWarnings?.length && <Alert variant="destructive"><AlertTriangle /><AlertTitle>Data Or Result Warning</AlertTitle><AlertDescription>{result.qualityWarnings.map((warning) => <p key={warning}>{warning}</p>)}</AlertDescription></Alert>}
    <Card className="gap-3 py-4"><CardHeader className="px-4"><CardTitle className="text-base">Benchmark Evidence</CardTitle><CardDescription>Risk and return comparisons use the same evaluation dates.</CardDescription></CardHeader><CardContent className="px-4"><div className="overflow-x-auto"><Table><TableCaption className="sr-only">Risk and return metrics for each comparison benchmark.</TableCaption><TableHeader><TableRow><TableHead>Benchmark</TableHead><TableHead>Return</TableHead><TableHead>CAGR</TableHead><TableHead>Drawdown</TableHead><TableHead>Volatility</TableHead></TableRow></TableHeader><TableBody>{Object.entries(metrics.benchmarkMetrics || {}).map(([label, values]) => <TableRow key={label}><TableCell className="font-medium">{label}</TableCell><TableCell>{number(values.totalReturn, "%")}</TableCell><TableCell>{number(values.cagr, "%")}</TableCell><TableCell className="text-destructive">{number(values.maxDrawdown, "%")}</TableCell><TableCell>{number(values.annualizedVolatility, "%")}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    <TradeHistoryPreview result={result} onOpen={onOpenTrades} />
  </div>
}

function Trades({ result }: { result: BacktestResult }) {
  if (!result.trades.length) return <div className="grid min-h-56 place-items-center rounded-lg border border-dashed text-sm text-muted-foreground">No trades were generated in this evaluation window.</div>
  return <div className="overflow-x-auto rounded-lg border"><Table><TableCaption className="sr-only">Trade ledger with entry, exit, profit and loss, holding period, and execution costs.</TableCaption><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Side</TableHead><TableHead>Entry</TableHead><TableHead>Entry Price</TableHead><TableHead>Exit / As Of</TableHead><TableHead>Exit Price</TableHead><TableHead>P&amp;L</TableHead><TableHead>Return</TableHead><TableHead>Bars</TableHead><TableHead>Cost</TableHead></TableRow></TableHeader><TableBody>{result.trades.map((trade, index) => <TableRow key={`${trade.entryDate}-${index}`}><TableCell><Badge variant={trade.status === "Open" ? "secondary" : "outline"}>{trade.status}</Badge></TableCell><TableCell>{trade.side}</TableCell><TableCell>{trade.entryDate}</TableCell><TableCell>{number(trade.entryPrice)}</TableCell><TableCell>{trade.exitDate || trade.asOfDate || "—"}</TableCell><TableCell>{number(trade.exitPrice)}</TableCell><TableCell className={cn(trade.pnl >= 0 ? "text-primary" : "text-destructive")}>{number(trade.pnl)}</TableCell><TableCell className={cn(trade.pnlPercent >= 0 ? "text-primary" : "text-destructive")}>{number(trade.pnlPercent, "%")}</TableCell><TableCell>{trade.barsHeld}</TableCell><TableCell>{number(trade.cost)}</TableCell></TableRow>)}</TableBody></Table></div>
}

function Robustness({ result, search }: { result: BacktestResult; search: ParameterSearchResponse | null }) {
  const scores = search?.heatmap.cells.map((cell) => cell.medianScore) || []
  const minimum = scores.length ? Math.min(...scores) : 0
  const maximum = scores.length ? Math.max(...scores) : 0
  return <div className="space-y-5">
    {search ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Search Method" value={search.method} detail={search.objective || "Median out-of-sample Calmar"} /><MetricCard label="Deflated Sharpe" value={number(search.deflatedSharpeProbability, "%", 1)} detail="Selection-adjusted probability" /><MetricCard label="Parameter Stability" value={search.stableParameters ? "Stable" : "Unstable"} detail={`${search.attempts.length} configurations recorded`} tone={search.stableParameters ? "positive" : "negative"} /><MetricCard label="Performance Decay" value={number(search.performanceDecay)} detail={`Final test began ${search.finalTestStart}`} tone={search.performanceDecay <= 0 ? "positive" : "negative"} /></div>{search.overfittingWarning && <Alert variant="destructive"><AlertTriangle /><AlertTitle>Overfitting Warning</AlertTitle><AlertDescription>{search.overfittingWarning}</AlertDescription></Alert>}<Card className="gap-3 py-4"><CardHeader className="px-4"><CardTitle className="text-base">Parameter Stability Map</CardTitle><CardDescription>Every attempted configuration remains visible; brighter cells scored better across walk-forward folds.</CardDescription></CardHeader><CardContent className="px-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{search.heatmap.cells.map((cell) => { const intensity = maximum === minimum ? 0.5 : (cell.medianScore - minimum) / (maximum - minimum); return <div key={`${cell.x}-${cell.y}`} className="rounded-md border p-3" style={{ backgroundColor: `rgba(182,245,89,${0.04 + intensity * 0.2})` }}><div className="font-mono text-xs">{search.heatmap.xParameter}: {cell.x}{search.heatmap.yParameter ? ` · ${search.heatmap.yParameter}: ${cell.y}` : ""}</div><div className="mt-2 text-lg font-semibold">{number(cell.medianScore)}</div><div className="text-[10px] text-muted-foreground">{cell.trials} trial{cell.trials === 1 ? "" : "s"}</div></div> })}</div></CardContent></Card></> : <Alert><Activity /><AlertTitle>Single Configuration Run</AlertTitle><AlertDescription>Mark one or more editable parameter chips as “Explore Range” to unlock guarded walk-forward search, an untouched final test, and parameter stability evidence.</AlertDescription></Alert>}
    {!!result.regimes?.length && <Card className="gap-3 py-4"><CardHeader className="px-4"><CardTitle className="text-base">Market Regimes</CardTitle><CardDescription>Descriptive slices of the selected evaluation window.</CardDescription></CardHeader><CardContent className="px-4"><Table><TableCaption className="sr-only">Strategy return and exposure grouped by descriptive market regime.</TableCaption><TableHeader><TableRow><TableHead>Regime</TableHead><TableHead>Sessions</TableHead><TableHead>Strategy Return</TableHead><TableHead>Average Exposure</TableHead></TableRow></TableHeader><TableBody>{result.regimes.map((regime) => <TableRow key={regime.regime}><TableCell>{regime.regime}</TableCell><TableCell>{regime.sessions}</TableCell><TableCell className={cn(regime.strategyReturn >= 0 ? "text-primary" : "text-destructive")}>{number(regime.strategyReturn, "%")}</TableCell><TableCell>{number(regime.averageExposure, "%", 1)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
  </div>
}

function Assumptions({ result }: { result: BacktestResult }) {
  const assumptions = result.assumptions
  return <div className="grid gap-4 lg:grid-cols-2"><Card className="gap-3 py-4"><CardHeader className="px-4"><CardTitle className="text-base">Execution Model</CardTitle><CardDescription>{result.executionModel}</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3 px-4 text-sm"><div><span className="text-muted-foreground">Initial Capital</span><p>{number(assumptions.initial_capital, "", 0)}</p></div><div><span className="text-muted-foreground">Commission</span><p>{number(assumptions.commission_bps, " bps")}</p></div><div><span className="text-muted-foreground">Slippage</span><p>{number(assumptions.slippage_bps, " bps")}</p></div><div><span className="text-muted-foreground">Cash Rate</span><p>{number(assumptions.annual_cash_rate * 100, "%")}</p></div></CardContent></Card><Card className="gap-3 py-4"><CardHeader className="px-4"><CardTitle className="text-base">Evaluation Window</CardTitle><CardDescription>Dates after indicator readiness and any holdout boundary.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3 px-4 text-sm"><div><span className="text-muted-foreground">Start</span><p>{result.evaluationPeriod.start}</p></div><div><span className="text-muted-foreground">End</span><p>{result.evaluationPeriod.end}</p></div><div><span className="text-muted-foreground">Sessions</span><p>{result.evaluationPeriod.sessions}</p></div><div><span className="text-muted-foreground">Benchmarks</span><p>{result.benchmarks?.join(", ") || "Buy & Hold, SPY"}</p></div></CardContent></Card></div>
}

export function EvidenceWorkspace({ result, search, runLabel }: { result: BacktestResult | null; search: ParameterSearchResponse | null; runLabel: string }) {
  const [activeTab, setActiveTab] = useState("overview")
  const openTrades = () => setActiveTab("trades")
  if (!result) return <Card className="rounded-none border-x-0 border-b-0 bg-card/60 shadow-none"><CardHeader><Badge variant="outline" className="w-fit"><BarChart3 />Evidence Workspace</Badge><CardTitle>Run research when the idea is ready.</CardTitle><CardDescription>The persistent chart supports exploration first. Results then appear here as benchmark-aware evidence, not a victory score.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-dashed p-4"><Activity className="size-5 text-primary" /><p className="mt-3 font-medium">Performance</p><p className="mt-1 text-xs text-muted-foreground">Strategy, passive, SPY, drawdown, and exposure.</p></div><div className="rounded-lg border border-dashed p-4"><Activity className="size-5 text-primary" /><p className="mt-3 font-medium">Current Signal</p><p className="mt-1 text-xs text-muted-foreground">Target state, rule values, timing, and latest transition.</p></div><div className="rounded-lg border border-dashed p-4"><ListChecks className="size-5 text-primary" /><p className="mt-3 font-medium">Trade Ledger</p><p className="mt-1 text-xs text-muted-foreground">Every entry, exit, open mark, cost, and P&amp;L.</p></div></CardContent></Card>
  return <Card className="rounded-none border-x-0 border-b-0 bg-card/60 shadow-none"><CardHeader className="border-b"><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge variant="outline" className="mb-2">Latest Evidence</Badge><CardTitle>{result.strategy.name}</CardTitle><CardDescription>{result.evaluationPeriod.start} → {result.evaluationPeriod.end} · {result.evaluationPeriod.sessions} sessions</CardDescription></div><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" onClick={openTrades}><History />Trade History<Badge variant="secondary">{result.trades.length}</Badge></Button><Badge className="text-xs">{result.verdict.label}</Badge></div></div></CardHeader><CardContent className="px-4 sm:px-6"><Tabs value={activeTab} onValueChange={setActiveTab} className="gap-5"><TabsList variant="line" className="w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Evidence &amp; Signal</TabsTrigger><TabsTrigger value="equity">Equity &amp; Drawdown</TabsTrigger><TabsTrigger value="trades">Trade History <Badge variant="secondary">{result.trades.length}</Badge></TabsTrigger><TabsTrigger value="advanced">Advanced Validation</TabsTrigger></TabsList><TabsContent value="overview"><Overview result={result} runLabel={runLabel} onOpenTrades={openTrades} /></TabsContent><TabsContent value="equity"><EquityDrawdownChart points={result.chart} /></TabsContent><TabsContent value="trades"><Trades result={result} /></TabsContent><TabsContent value="advanced"><div className="space-y-6"><Robustness result={result} search={search} /><Assumptions result={result} /></div></TabsContent></Tabs></CardContent></Card>
}
