import { useEffect, useMemo, useState } from "react"
import { Activity, AlertTriangle, Clock3, FlaskConical, GitBranch, Landmark, ShieldAlert } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Slider } from "@/components/ui/slider"
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { OptionLineChart, type OptionChartSeries } from "@/features/option-lab/option-line-chart"
import type { OptionSimulationResult } from "@/lib/types"

const pathColors = ["#b6f559", "#64d5c7", "#f8bd5e", "#a78bfa", "#ff6a6a", "#7dd3fc", "#f0abfc", "#facc15", "#4ade80", "#fb7185", "#c4b5fd", "#2dd4bf"]

function money(value: number) {
  return value.toLocaleString(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 2 })
}

function summaryValue(value: number | "Unlimited") {
  return typeof value === "number" ? money(value) : value
}

function Metric({ label, value, note, negative = false }: { label: string; value: string; note: string; negative?: boolean }) {
  return <div className="rounded-lg border bg-background/50 p-4"><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-muted-foreground">{label}</p><strong className={negative ? "mt-2 block text-lg text-destructive" : "mt-2 block text-lg"}>{value}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{note}</span></div>
}

export function ScenarioWorkspace({ simulation, loading }: { simulation: OptionSimulationResult | null; loading: boolean }) {
  const [timelineIndex, setTimelineIndex] = useState(0)
  useEffect(() => setTimelineIndex(0), [simulation])
  const payoffSeries = useMemo<OptionChartSeries[]>(() => simulation ? [{ label: "Position P&L", color: "#b6f559", points: simulation.payoff.map((point) => ({ independentValue: point.underlyingPrice, value: point.pnl })) }] : [], [simulation])
  const selectedSlice = simulation?.surface[Math.min(timelineIndex, Math.max(simulation.surface.length - 1, 0))]
  const sliceSeries = useMemo<OptionChartSeries[]>(() => selectedSlice ? [{ label: "Modeled P&L", color: "#64d5c7", points: selectedSlice.points.map((point) => ({ independentValue: point.underlyingPrice, value: point.pnl })) }] : [], [selectedSlice])
  const underlyingPaths = useMemo<OptionChartSeries[]>(() => simulation?.monteCarlo.slice(0, 12).map((path, index) => ({ label: `Path ${path.path}`, color: pathColors[index], points: path.points.map((point) => ({ independentValue: point.day, value: point.underlyingPrice })) })) || [], [simulation])
  const pnlPaths = useMemo<OptionChartSeries[]>(() => simulation?.monteCarlo.slice(0, 12).map((path, index) => ({ label: `Path ${path.path}`, color: pathColors[index], points: path.points.map((point) => ({ independentValue: point.day, value: point.positionPnl })) })) || [], [simulation])

  if (!simulation) return <Card id="option-evidence" className="min-h-[560px] border-dashed bg-card/40"><CardContent className="grid flex-1 place-items-center py-16"><div className="max-w-lg text-center"><div className="mx-auto grid size-14 place-items-center rounded-full border border-primary/30 bg-primary/10 text-primary"><FlaskConical className={loading ? "motion-safe:animate-pulse" : ""} /></div><h2 className="mt-5 text-xl font-semibold">{loading ? "Calculating scenarios…" : "Build a position, then inspect its lifecycle."}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">The lab will calculate American-model value, expiry payoff, Greeks, price/time slices, and model-based paths. It is a theoretical simulation, not a historical option backtest.</p></div></CardContent></Card>

  const maximumLossIsNegative = simulation.summary.maximumLoss === "Unlimited" || (typeof simulation.summary.maximumLoss === "number" && simulation.summary.maximumLoss < 0)
  return <section id="option-evidence" aria-labelledby="option-evidence-title" className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><Badge variant="outline" className="border-primary/30 text-primary">{simulation.historicalStatus}</Badge><Badge variant="secondary">American Model</Badge><Badge variant="outline">Run {simulation.runId.slice(0, 8)}</Badge></div><h2 id="option-evidence-title" className="text-2xl font-semibold">Position evidence</h2><p className="mt-1 text-sm text-muted-foreground">Payoff and exposure under explicit price, time, volatility, rate, and dividend assumptions.</p></div><div className="font-mono text-[10px] text-muted-foreground">VALUED {simulation.assumptions.valuationDate} · {simulation.modelVersion} · MULTIPLIER {simulation.assumptions.contractMultiplier}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="Break-Even" value={simulation.summary.breakEvens.length ? simulation.summary.breakEvens.map(money).join(" · ") : "None In Range"} note="At expiry" />
      <Metric label="Maximum Gain" value={summaryValue(simulation.summary.maximumGain)} note="Within modeled structure" />
      <Metric label="Maximum Loss" value={summaryValue(simulation.summary.maximumLoss)} note="Before taxes and broker rules" negative={maximumLossIsNegative} />
      <Metric label="Collateral" value={money(simulation.summary.collateral)} note="Simplified paper reserve" />
      <Metric label="Assignment Exposure" value={money(simulation.summary.assignmentExposure)} note="Short-leg strike notional" />
    </div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Share Outlay" value={money(simulation.positionProfile.shareOutlay)} note="At configured cost basis" /><Metric label="Long Premium Debit" value={money(simulation.positionProfile.longPremiumDebit)} note="Premium paid" /><Metric label="Short Premium Credit" value={money(simulation.positionProfile.shortPremiumCredit)} note="Premium received" /><Metric label="Capital Committed" value={money(simulation.positionProfile.netCapitalCommitted)} note="Simplified initial cash" /><Metric label="Risk Shape" value={simulation.positionProfile.riskLabel} note="Before broker-specific margin" negative={simulation.positionProfile.riskLabel.toLowerCase().includes("uncapped")} /></div>
    <Tabs defaultValue="payoff" className="rounded-xl border bg-card/65 p-3 sm:p-4">
      <TabsList variant="line" className="max-w-full overflow-x-auto"><TabsTrigger value="payoff">Expiry Payoff</TabsTrigger><TabsTrigger value="time">Price × Time</TabsTrigger><TabsTrigger value="paths">Modeled Paths</TabsTrigger><TabsTrigger value="greeks">Greeks</TabsTrigger><TabsTrigger value="playbook">Decision Playbook</TabsTrigger>{simulation.conversionAnalysis && <TabsTrigger value="financing">Financing</TabsTrigger>}</TabsList>
      <TabsContent value="payoff" className="mt-4"><OptionLineChart series={payoffSeries} independentLabel="Underlying Price" valueLabel="Position P&L" ariaLabel="Option position profit and loss at expiry across underlying prices" /></TabsContent>
      <TabsContent value="time" className="mt-4 space-y-4">
        <div className="flex flex-col gap-3 rounded-lg border bg-background/40 p-4 sm:flex-row sm:items-center"><Clock3 className="size-4 text-primary" /><div className="min-w-28"><div className="font-mono text-[9px] uppercase tracking-[0.12em] text-muted-foreground">Timeline</div><strong>{selectedSlice?.day ? `Day ${selectedSlice.day}` : "Entry"}</strong></div><Slider aria-label="Modeled day from entry to expiry" value={[timelineIndex]} min={0} max={Math.max(simulation.surface.length - 1, 0)} step={1} onValueChange={(values) => setTimelineIndex(values[0])} /><Badge variant="outline">{simulation.surface.length} slices</Badge></div>
        <OptionLineChart series={sliceSeries} independentLabel="Underlying Price" valueLabel="Modeled P&L" ariaLabel={`Modeled option profit and loss after ${selectedSlice?.day || 0} days`} />
      </TabsContent>
      <TabsContent value="paths" className="mt-4 space-y-4"><div className="grid gap-4 2xl:grid-cols-2"><div><div className="mb-2 flex items-center gap-2"><Activity className="size-4 text-primary" /><h3 className="text-sm font-semibold">Underlying Paths</h3></div><OptionLineChart series={underlyingPaths} independentLabel="Day" valueLabel="Underlying Price" ariaLabel="Animated modeled underlying price paths" animate /></div><div><div className="mb-2 flex items-center gap-2"><Activity className="size-4 text-chart-2" /><h3 className="text-sm font-semibold">Position P&L Paths</h3></div><OptionLineChart series={pnlPaths} independentLabel="Day" valueLabel="Position P&L" ariaLabel="Animated modeled option position profit and loss paths" animate /></div></div><p className="text-xs leading-5 text-muted-foreground">Paths use the configured implied volatility and random seed. They explore possible model outcomes; they are not forecasts or probabilities of profit.</p></TabsContent>
      <TabsContent value="greeks" className="mt-4 overflow-x-auto"><Table><TableCaption>American-model Greeks are scaled by contract side, quantity, and multiplier.</TableCaption><TableHeader><TableRow><TableHead>Leg</TableHead><TableHead>Strike</TableHead><TableHead>American</TableHead><TableHead>European</TableHead><TableHead>Delta</TableHead><TableHead>Gamma</TableHead><TableHead>Theta</TableHead><TableHead>Vega</TableHead><TableHead>Prob. ITM</TableHead></TableRow></TableHeader><TableBody>{simulation.greeks.map((leg) => <TableRow key={leg.legId}><TableCell><Badge variant={leg.side === "long" ? "secondary" : "outline"}>{leg.side.toUpperCase()} {leg.optionType.toUpperCase()}</Badge></TableCell><TableCell>{money(leg.strike)}</TableCell><TableCell>{money(leg.americanPrice)}</TableCell><TableCell>{money(leg.blackScholesPrice)}</TableCell><TableCell>{leg.delta.toFixed(4)}</TableCell><TableCell>{leg.gamma.toFixed(4)}</TableCell><TableCell>{leg.theta.toFixed(4)}</TableCell><TableCell>{leg.vega.toFixed(4)}</TableCell><TableCell>{leg.probabilityInTheMoney.toFixed(1)}%</TableCell></TableRow>)}</TableBody></Table></TabsContent>
      <TabsContent value="playbook" className="mt-4 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border bg-background/40 p-4"><div><div className="flex items-center gap-2"><GitBranch className="size-4 text-primary" /><h3 className="font-semibold">{simulation.managementPlaybook.title}</h3></div><p className="mt-1 text-xs text-muted-foreground">Branches are alternatives to inspect, not an automated recommendation.</p></div><Badge variant={simulation.managementPlaybook.riskLabel.toLowerCase().includes("uncapped") ? "destructive" : "outline"}>{simulation.managementPlaybook.riskLabel}</Badge></div><div className="grid gap-3 lg:grid-cols-2">{simulation.managementPlaybook.branches.map((branch) => <Card key={branch.id} className="gap-3 py-4"><CardHeader className="px-4"><div className="flex items-start justify-between gap-2"><CardTitle className="text-sm">{branch.title}</CardTitle><Badge variant="secondary">{branch.eventType.replaceAll("_", " ")}</Badge></div><CardDescription>{branch.trigger}</CardDescription></CardHeader><CardContent className="space-y-3 px-4 text-xs"><div><span className="font-mono text-[8px] text-muted-foreground">ACTION</span><strong className="mt-1 block">{branch.action}</strong></div>{branch.requiredCash !== undefined && <div><span className="font-mono text-[8px] text-muted-foreground">ASSUMED CASH</span><strong className="mt-1 block">{money(branch.requiredCash)}</strong></div>}<p className="leading-5 text-muted-foreground">{branch.impact}</p>{branch.warnings.map((warning) => <p key={warning} className="rounded-md border border-chart-3/30 bg-chart-3/5 p-2 text-chart-3"><AlertTriangle className="mr-1 inline size-3" />{warning}</p>)}</CardContent></Card>)}</div></TabsContent>
      {simulation.conversionAnalysis && <TabsContent value="financing" className="mt-4 space-y-4"><div className="rounded-lg border border-primary/30 bg-primary/5 p-4"><div className="flex items-center gap-2"><Landmark className="size-4 text-primary" /><h3 className="font-semibold">Locked Payoff Is Not Unconditional Risk-Free Profit</h3></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{simulation.conversionAnalysis.interpretation}</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Net Capital" value={money(simulation.conversionAnalysis.netCapitalCommitted)} note="Shares + put − call credit" /><Metric label="Locked Proceeds" value={money(simulation.conversionAnalysis.lockedTerminalProceeds)} note={`After ${simulation.conversionAnalysis.holdingDays} days`} /><Metric label="Nominal Profit" value={money(simulation.conversionAnalysis.nominalProfit)} note={`${simulation.conversionAnalysis.nominalReturnPercent.toFixed(2)}% total`} /><Metric label="Annualized Return" value={`${simulation.conversionAnalysis.annualizedReturnPercent.toFixed(2)}%`} note={`${simulation.conversionAnalysis.annualizedExcessVsCashPercent.toFixed(2)}% vs configured cash rate`} negative={simulation.conversionAnalysis.annualizedExcessVsCashPercent < 0} /></div><p className="text-xs text-muted-foreground">Configured cash rate {simulation.conversionAnalysis.configuredCashRatePercent.toFixed(2)}% · dividend-yield assumption {simulation.conversionAnalysis.dividendYieldAssumptionPercent.toFixed(2)}%. Executable bid/ask prices and assignment timing determine realized return.</p></TabsContent>}
    </Tabs>
    <Card className="gap-3 py-4"><CardHeader className="px-4 sm:px-6"><div className="flex items-center gap-2"><ShieldAlert className="size-4 text-chart-3" /><CardTitle className="text-sm">Model Boundaries</CardTitle></div><CardDescription>{simulation.model}; {simulation.comparisonModel} is shown only as an educational comparison.</CardDescription></CardHeader><CardContent className="px-4 sm:px-6"><ul className="space-y-2 text-xs leading-5 text-muted-foreground">{simulation.limitations.map((limitation) => <li key={limitation}>• {limitation}</li>)}</ul></CardContent></Card>
  </section>
}
