from __future__ import annotations

from datetime import datetime, timezone

from .evidence_repository import EvidenceRepository
from .guidance_models import (
    GuidanceComparison,
    GuidanceEvaluation,
    GuidanceEvaluationCreate,
    GuidanceEvaluationMethod,
    GuidanceEvidence,
    GuidanceHistory,
    GuidanceQuery,
    GuidanceRecord,
    GuidanceRevisionDirection,
    GuidanceStatement,
    GuidanceStatementCreate,
    GuidanceStatus,
    GuidanceValueKind,
    GuidanceWithdrawalCreate,
)
from .guidance_repository import GuidanceRepository
from .metric_models import MetricPeriodKind
from .metrics import NormalizedMetricsService
from .service import CompanyIdentityService


class GuidanceService:
    def __init__(
        self,
        repository: GuidanceRepository,
        evidence: EvidenceRepository,
        identities: CompanyIdentityService,
        metrics: NormalizedMetricsService | None = None,
    ) -> None:
        self.repository = repository
        self.evidence = evidence
        self.identities = identities
        self.metrics = metrics

    def history(self, ticker: str, query: GuidanceQuery) -> GuidanceHistory:
        company = self._company(ticker)
        as_of = (query.as_of or datetime.now(timezone.utc)).astimezone(timezone.utc)
        statements = self.repository.list_statements(
            company.company_id,
            query.model_copy(update={"as_of": as_of}),
        )
        by_id = {statement.statement_id: statement for statement in statements}
        records = []
        withheld = 0
        for statement in statements:
            evaluations = self.repository.list_evaluations(statement.statement_id, as_of)
            status = evaluations[-1].status if evaluations else GuidanceStatus.OPEN
            if query.statuses and status not in query.statuses:
                continue
            statement_evidence = self._evidence(
                company.company_id,
                "guidance_statement",
                statement.statement_id,
                as_of,
            )
            if not statement_evidence:
                withheld += 1
                continue
            records.append(
                GuidanceRecord(
                    statement=statement,
                    revision_direction=self._revision_direction(
                        by_id.get(statement.supersedes_statement_id),
                        statement,
                    ),
                    status=status,
                    evaluations=evaluations,
                    statement_evidence=statement_evidence,
                    evaluation_evidence={
                        evaluation.evaluation_id: self._evidence(
                            company.company_id,
                            "guidance_evaluation",
                            evaluation.evaluation_id,
                            as_of,
                        )
                        for evaluation in evaluations
                    },
                )
            )
        warnings = [
            "Guidance and commitments are historical source-backed statements, not forecasts generated by GBB Terminal."
        ]
        if withheld:
            warnings.append(
                f"{withheld} statement(s) were withheld because inspectable source evidence was unavailable."
            )
        if not records:
            warnings.append("No source-backed guidance or management commitments are available inside this boundary.")
        warnings.append(
            "Qualitative delivery assessments remain manual or interpretive unless an objective normalized result supports a rule-based outcome."
        )
        return GuidanceHistory(company=company, as_of=as_of, records=records, warnings=warnings)

    def save_statement(self, command: GuidanceStatementCreate) -> GuidanceStatement:
        return self.repository.save_statement(command)

    def save_evaluation(self, command: GuidanceEvaluationCreate) -> GuidanceEvaluation:
        return self.repository.save_evaluation(command)

    def withdraw(
        self,
        ticker: str,
        statement_id: str,
        command: GuidanceWithdrawalCreate,
    ) -> GuidanceEvaluation:
        company = self._company(ticker)
        statement = self.repository.get_statement(statement_id)
        if statement.company_id != company.company_id:
            raise LookupError(f"Guidance statement {statement_id} is not associated with {ticker.upper()}.")
        return self.repository.save_evaluation(
            GuidanceEvaluationCreate(
                statement_id=statement_id,
                status=GuidanceStatus.WITHDRAWN,
                evaluated_at=command.known_at,
                known_at=command.known_at,
                method=GuidanceEvaluationMethod.SYSTEM,
                evidence_span_ids=command.evidence_span_ids,
                note=command.note,
            )
        )

    def evaluate_numeric(
        self,
        ticker: str,
        statement_id: str,
        actual_value: float,
        actual_unit: str,
        known_at: datetime,
        source_fact_ids: list[str],
        evidence_span_ids: list[str] | None = None,
    ) -> GuidanceEvaluation:
        company = self._company(ticker)
        statement = self.repository.get_statement(statement_id)
        if statement.company_id != company.company_id:
            raise LookupError(f"Guidance statement {statement_id} is not associated with {ticker.upper()}.")
        if statement.value_kind == GuidanceValueKind.QUALITATIVE:
            raise ValueError("Qualitative guidance cannot receive an automatic numeric outcome.")
        if statement.unit != actual_unit:
            raise ValueError(f"Guidance outcome unit {actual_unit} does not match statement unit {statement.unit}.")
        if statement.comparison == GuidanceComparison.WITHIN_RANGE:
            delivered = statement.lower_bound <= actual_value <= statement.upper_bound
        elif statement.comparison == GuidanceComparison.AT_LEAST:
            delivered = actual_value >= statement.point_value
        elif statement.comparison == GuidanceComparison.AT_MOST:
            delivered = actual_value <= statement.point_value
        else:
            raise ValueError(
                "Approximately-valued guidance requires an explicit manual tolerance and cannot be auto-evaluated."
            )
        return self.repository.save_evaluation(
            GuidanceEvaluationCreate(
                statement_id=statement_id,
                status=GuidanceStatus.DELIVERED if delivered else GuidanceStatus.MISSED,
                evaluated_at=known_at,
                known_at=known_at,
                method=GuidanceEvaluationMethod.RULE_BASED,
                actual_value=actual_value,
                actual_unit=actual_unit,
                source_fact_ids=source_fact_ids,
                evidence_span_ids=evidence_span_ids or [],
                note="Objective result compared with the persisted statement bounds.",
            )
        )

    def evaluate_from_metrics(
        self,
        ticker: str,
        statement_id: str,
        as_of: datetime | None = None,
    ) -> GuidanceEvaluation:
        if self.metrics is None:
            raise RuntimeError("Normalized metrics are not configured for guidance reconciliation.")
        statement = self.repository.get_statement(statement_id)
        if not statement.metric_id or not statement.applicable_period_end:
            raise ValueError("Automatic reconciliation requires metric_id and applicable_period_end.")
        period_kind = (
            MetricPeriodKind.ANNUAL
            if (statement.fiscal_period or "").upper() in {"FY", "ANNUAL"}
            else MetricPeriodKind.QUARTERLY
        )
        effective_as_of = (as_of or datetime.now(timezone.utc)).astimezone(timezone.utc)
        metric_set = self.metrics.calculate(ticker, period_kind=period_kind, as_of=effective_as_of)
        metric = next(
            (
                item
                for item in metric_set.metrics
                if item.metric_id == statement.metric_id
                and item.period_end == statement.applicable_period_end
                and item.value is not None
            ),
            None,
        )
        if metric is None:
            raise LookupError("No exact normalized result is available for this guidance period and metric.")
        return self.evaluate_numeric(
            ticker,
            statement_id,
            metric.value,
            metric.unit,
            effective_as_of,
            metric.source_fact_ids,
        )

    def _evidence(
        self,
        company_id: str,
        claim_type: str,
        claim_id: str,
        as_of: datetime,
    ) -> list[GuidanceEvidence]:
        result = []
        for claim_span in self.evidence.list_claim_spans(company_id, claim_type, claim_id, as_of):
            document = self.evidence.get_document(claim_span.span.document_id)
            if document is not None:
                result.append(
                    GuidanceEvidence(
                        link=claim_span.link,
                        document=document,
                        span=claim_span.span,
                    )
                )
        return result

    def _company(self, ticker: str):
        company = self.identities.resolve_ticker(ticker)
        if company is None:
            raise LookupError(f"No canonical company identity exists for ticker {ticker.upper()}.")
        return company

    @staticmethod
    def _revision_direction(
        prior: GuidanceStatement | None,
        current: GuidanceStatement,
    ) -> GuidanceRevisionDirection:
        if prior is None:
            return GuidanceRevisionDirection.INITIAL
        prior_value = GuidanceService._representative_value(prior)
        current_value = GuidanceService._representative_value(current)
        if prior_value is None or current_value is None or prior.unit != current.unit:
            return GuidanceRevisionDirection.CHANGED
        if abs(current_value - prior_value) <= max(abs(prior_value), 1) * 1e-9:
            return GuidanceRevisionDirection.REAFFIRMED
        return (
            GuidanceRevisionDirection.RAISED
            if current_value > prior_value
            else GuidanceRevisionDirection.CUT
        )

    @staticmethod
    def _representative_value(statement: GuidanceStatement) -> float | None:
        if statement.value_kind == GuidanceValueKind.NUMERIC_RANGE:
            return (statement.lower_bound + statement.upper_bound) / 2
        if statement.value_kind == GuidanceValueKind.NUMERIC_POINT:
            return statement.point_value
        return None
